### PR TITLE
#161382343 Setup environment for writing tests

### PR DESCRIPTION
**Pull request by emukungu**
#### What does this PR do?
Setup environment for writing tests

#### Description of Task to be completed?
All components should have end to end tests

#### How should this be manually tested?
 - Clone the repository.
 - Install application dependencies using`yarn`
 - run the server using `yarn start:dev`
 - run the tests using `yarn test`

#### What are the relevant pivotal tracker stories?
#161382343

#### Screenshots 
screen shot 2018-11-27 at 2 25 20 pm

### CODE REVIEW

**Review by johnkegz — COMMENTED** [review]
@emukungu try fixing the issues raised by Hound.

**Review by johnkegz — COMMENTED** [review]
@emukungu , wait for Cedric's PR to be merged and then rebase because he has reconfigured hound

**Comment by shakirandagire** [comment]
@emukungu Could you squash your commits

**Comment by cdvx** [comment]
@emukungu Could you squash commits, and also rebase to get the new changes from develop

**Review by cdvx — CHANGES_REQUESTED** [review]
@emukungu Please delete the `eslintrc.js` file, we are now using the `eslintrc.json` file instead

**Pull request closed without merging**
