### PR TITLE
#162440001 Fix folder structure

### PR DESCRIPTION
**Pull request by cdvx**
#### What does this PR do?
Fix folder structure

#### Description of Task to be completed?
Fix folder structure for `Authors' Haven` frontend app

#### How should this be manually tested?
When one clones the repo, there should be only one `components` directory in the `src` folder.

#### Any background context you want to provide?
To test this out, one has to download and install `nodejs` locally (on the development machine)
install yarn `brew install yarn`
clone the repository
`git clone https://github.com/andela/ah-frontend-thor.git`

Then install the dependencies with
`yarn install` or `yarn`

#### What are the relevant pivotal tracker stories?
#162440001

### CODE REVIEW

**Review by johnkegz — COMMENTED** [review]
@cdvx for me, am still seeing two component folders. The same found in develop

**Review by johnkegz — COMMENTED** [review]
@cdvx the new PR you have made has a test for App.jsx which no longer exist, remember its now AppRouter.jsx that is rendered in the root of index.html.

**Review by johnkegz — COMMENTED** [review]
@cdvx Am still seeing two folders.

**Comment by cdvx** [comment]
@johnkegz  The other folder has been removed

**Review by joshNic — APPROVED** [review]
LDTM

**Review by johnkegz — APPROVED** [review]
@cdvx well done

**Pull request merged**
