### PR TITLE
#162265767 Correct issue with hound and eslint configuration

### PR DESCRIPTION
**Pull request by cdvx**
#### What does this PR do?
Setup and customize Hound-Github integration

#### Description of Task to be completed?
Makes sure ESlint config and hound are configured to check for style violations

#### How should this be manually tested?
Raise a PR and Hound will make a review based on es6 coding style conventions.

#### Any background context you want to provide?
To test this out, one has to download and install `nodejs` locally (on the development machine)
install yarn `brew install yarn`
clone the repository
`git clone https://github.com/andela/ah-frontend-thor.git`

Then install the dependencies with
`yarn install` or `yarn`

#### What are the relevant pivotal tracker stories?
#162265767

### CODE REVIEW

**Review by johnkegz — APPROVED** [review]
Good work @cdvx

**Comment by shakirandagire** [comment]
@cdvx Could you squash the commits and also use this format to write the PR names(#[STORY_ID] [Story description]
)

**Comment by emukungu** [comment]
When squashing follow the standard for the commits.

**Review by bozicschucky — APPROVED** [review]
Looks good to me.

**Comment by cdvx** [comment]
> When squashing follow the standard for the commits.

@emukungu Commits have been squashed

**Comment by cdvx** [comment]
> @cdvx Could you squash the commits and also use this format to write the PR names(#[STORY_ID] [Story description]
> )

Fixed it, thanks! @shakirandagire

**Pull request merged**
